import { flushPromises, mount } from '@vue/test-utils'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { enableAutoUnmount } from '@vue/test-utils'
import BillingPanel from './BillingPanel.vue'
import { billingRequest } from '../services/billing-api'
vi.mock('../services/billing-api', () => ({ billingRequest: vi.fn(), trustedBillingUrl: vi.fn(value => value) }))
beforeEach(() => vi.clearAllMocks())
enableAutoUnmount(afterEach)
describe('billing panel', () => {
  it('shows canceled renewal for an active subscription with only cancel_at set', async () => {
    billingRequest.mockResolvedValue({ enabled: true, payments: [], subscriptions: [{ status: 'active', cancelAtPeriodEnd: false, cancelAt: 1793206800, renewalCanceled: true, periodEnd: 1793206800 }] })
    const wrapper = mount(BillingPanel, { props: { idToken: 'token' } })
    await flushPromises()
    expect(wrapper.get('.renewal-off').text()).toContain('ยกเลิกต่ออายุแล้ว')
    expect(wrapper.text()).toContain('ยังใช้ Premium ได้ถึง')
    expect(wrapper.text()).not.toContain('เปิดต่ออายุอัตโนมัติ')
  })
  it('refreshes cancellation after returning from Stripe and removes listeners on unmount', async () => {
    const active = { enabled: true, payments: [], hasCustomer: true, subscriptions: [{ status: 'active', cancelAtPeriodEnd: false, periodEnd: 1793206800 }] }
    billingRequest.mockResolvedValueOnce(active)
    const wrapper = mount(BillingPanel, { props: { idToken: 'token' } })
    await flushPromises()
    expect(wrapper.text()).toContain('เปิดต่ออายุอัตโนมัติ')
    const canceled = { ...active, subscriptions: [{ ...active.subscriptions[0], cancelAtPeriodEnd: true }] }
    billingRequest.mockResolvedValue(canceled)
    window.dispatchEvent(new Event('focus'))
    await flushPromises()
    expect(wrapper.get('.renewal-off').text()).toContain('ยกเลิกต่ออายุแล้ว')
    expect(wrapper.text()).toContain('ยังใช้ Premium ได้ถึง')
    expect(wrapper.text()).not.toContain('เปิดต่ออายุอัตโนมัติ')
    expect(wrapper.emitted('refresh-account').at(-1)).toEqual([canceled])
    wrapper.unmount()
    billingRequest.mockClear()
    window.dispatchEvent(new Event('focus'))
    expect(billingRequest).not.toHaveBeenCalled()
  })
  it('does not promise continued access for an ended subscription', async () => {
    billingRequest.mockResolvedValue({ enabled: true, payments: [], subscriptions: [{ status: 'canceled', cancelAtPeriodEnd: true }] })
    const wrapper = mount(BillingPanel, { props: { idToken: 'token' } })
    await flushPromises()
    expect(wrapper.find('.renewal-off').exists()).toBe(false)
    expect(wrapper.text()).not.toContain('ยังใช้ Premium ได้ถึง')
  })
  it('never opens Checkout automatically for the local mock or a return URL', async () => {
    const wrapper = mount(BillingPanel, { props: { local: true, product: 'yearly' } })
    await flushPromises()
    expect(billingRequest).not.toHaveBeenCalled()
    expect(wrapper.text()).toContain('ยังจ่ายผ่าน Stripe ไม่ได้')
    expect(wrapper.text()).not.toContain('ไปชำระเงินทดสอบบน Stripe')
  })
  it('requires an explicit payment click and shows recurring consent', async () => {
    billingRequest.mockResolvedValue({ enabled: true, payments: [], subscriptions: [], hasCustomer: false })
    const wrapper = mount(BillingPanel, { props: { idToken: 'token', product: 'yearly' } })
    await flushPromises()
    expect(billingRequest).toHaveBeenCalledTimes(1)
    expect(billingRequest).toHaveBeenCalledWith({ idToken: 'token', action: 'status' })
    expect(wrapper.get('.price-summary').text()).toContain('999 บาท')
    expect(wrapper.get('a[href="/terms.html"]').attributes('rel')).toBe('noopener')
    expect(wrapper.get('a[href="/privacy.html"]').exists()).toBe(true)
    expect(wrapper.get('.price-summary').text()).toContain('ไม่ต่ออายุอัตโนมัติ')
    expect(wrapper.get('.pay-button').text()).toContain('QR PromptPay')
    await wrapper.findAll('.method')[1].trigger('click')
    expect(wrapper.get('.price-summary').text()).toContain('999 บาท / ปี')
    expect(wrapper.text()).toContain('ต่ออายุอัตโนมัติ')
    expect(wrapper.emitted('refresh-account')).toHaveLength(1)
  })
  it('reports unavailable billing without displaying a false success', async () => {
    billingRequest.mockRejectedValue(new Error('ระบบชำระเงินทดสอบยังตั้งค่าไม่ครบ'))
    const wrapper = mount(BillingPanel, { props: { idToken: 'token', product: 'monthly' } })
    await flushPromises()
    expect(wrapper.get('[role="alert"]').text()).toContain('ยังตั้งค่าไม่ครบ')
    expect(wrapper.emitted('refresh-account')).toEqual([[null]])
    expect(wrapper.get('.pay-button').element.disabled).toBe(true)
  })
  it('shows Live history without a test badge or a recurring price on a past payment', async () => {
    billingRequest.mockResolvedValue({ enabled: true, testMode: false, payments: [{ id: 'payment', product: 'monthly', amount: 14900, created_at: '2026-10-02T05:00:00Z', payment_method: 'promptpay' }], subscriptions: [], hasCustomer: true })
    const wrapper = mount(BillingPanel, { props: { idToken: 'token' } })
    await flushPromises()
    expect(wrapper.text()).not.toContain('ทดสอบ')
    expect(wrapper.get('li').text()).toContain('PromptPay')
    expect(wrapper.get('li').text()).toContain('149 บาท')
    expect(wrapper.get('li').text()).not.toContain('บาท/เดือน')
  })
  it('explains the prepaid annual start and defers the next card charge', async () => {
    billingRequest.mockResolvedValue({ enabled: true, payments: [], subscriptions: [] })
    const wrapper = mount(BillingPanel, { props: { idToken: 'token', product: 'yearly', advanceStartsAt: '2026-11-01T05:00:00Z' } })
    await flushPromises()
    expect(wrapper.get('.advance-notice').text()).toContain('จ่าย 999 บาทวันนี้')
    expect(wrapper.get('.advance-notice').text()).toContain('ยกเลิกต่ออายุรายเดือนเมื่อชำระสำเร็จ')
    await wrapper.findAll('.method')[1].trigger('click')
    expect(wrapper.get('.advance-notice').text()).toContain('ไม่เรียกเก็บซ้ำในวันเริ่มรายปี')
    expect(billingRequest).toHaveBeenCalledTimes(1)
  })
  it('keeps same-package PromptPay extensions from switching to card', async () => {
    billingRequest.mockResolvedValue({ enabled: true, payments: [], subscriptions: [] })
    const wrapper = mount(BillingPanel, { props: { idToken: 'token', product: 'monthly', promptpayOnly: true } })
    await flushPromises()
    expect(wrapper.findAll('.method')[1].element.disabled).toBe(true)
    expect(wrapper.text()).toContain('เพิ่มเวลาจากวันหมดอายุเดิม')
  })
  it('allows retry after a status failure without creating a checkout', async () => {
    billingRequest.mockRejectedValueOnce(new Error('เชื่อมระบบชำระเงินไม่ได้'))
    const wrapper = mount(BillingPanel, { props: { idToken: 'token', product: 'comparison' } })
    await flushPromises()
    expect(wrapper.get('.pay-button').element.disabled).toBe(true)
    billingRequest.mockResolvedValueOnce({ enabled: true, payments: [], subscriptions: [] })
    await wrapper.findAll('button').at(-1).trigger('click')
    await flushPromises()
    expect(wrapper.find('[role="alert"]').exists()).toBe(false)
    expect(wrapper.get('.pay-button').element.disabled).toBe(false)
    expect(wrapper.get('.price-summary').text()).toContain('59 บาท')
    expect(billingRequest.mock.calls.every(([request]) => request.action === 'status')).toBe(true)
  })
  it('requires sign-in and blocks payment while the initial status is loading', async () => {
    const wrapper = mount(BillingPanel, { props: { product: 'monthly' } })
    expect(wrapper.text()).toContain('กรุณาเข้าสู่ระบบ LINE')
    expect(wrapper.get('.pay-button').element.disabled).toBe(true)
    let resolve
    billingRequest.mockReturnValue(new Promise(done => { resolve = done }))
    await wrapper.setProps({ idToken: 'token' })
    expect(wrapper.text()).toContain('กำลังตรวจสอบข้อมูลการชำระเงิน')
    expect(wrapper.get('.pay-button').element.disabled).toBe(true)
    resolve({ enabled: true, payments: [], subscriptions: [] })
    await flushPromises()
    expect(wrapper.get('.pay-button').element.disabled).toBe(false)
  })
  it('identifies the failing annual subscription without promising renewal rights', async () => {
    billingRequest.mockResolvedValue({ enabled: true, payments: [], hasCustomer: true, subscriptions: [{ status: 'past_due', billingCycle: 'yearly', periodEnd: 1793206800 }] })
    const wrapper = mount(BillingPanel, { props: { idToken: 'token' } })
    await flushPromises()
    expect(wrapper.get('.subscription-status').text()).toContain('Premium รายปี')
    expect(wrapper.text()).toContain('ยังไม่ยืนยันการชำระรอบใหม่')
    expect(wrapper.text()).not.toContain('เปิดต่ออายุอัตโนมัติ')
  })
})
